Post http://localhost:5000/api/node
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIyIiwic2lkIjoiMSIsImV4cCI6MTYyOTkxMDg5NiwiaXNzIjoiRXRlZEFwaS5jb20iLCJhdWQiOiJFdGVkQXBpLmNvbSJ9.k2Hk5HLlYwlKRy4709B3UuUV0y93lbJg4uBtBofA_Eg

{
  "name": "testSub3",
  "zone": "testZone3",
  "phase": "testPhase3"
}

###
Get http://137.184.75.4:5000/api/node
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIyIiwic2lkIjoiMSIsImV4cCI6MTYyOTkxMDg5NiwiaXNzIjoiRXRlZEFwaS5jb20iLCJhdWQiOiJFdGVkQXBpLmNvbSJ9.k2Hk5HLlYwlKRy4709B3UuUV0y93lbJg4uBtBofA_Eg

###
Get http://137.184.75.4:5000/api/node/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIyIiwic2lkIjoiMSIsImV4cCI6MTYyOTkxMDg5NiwiaXNzIjoiRXRlZEFwaS5jb20iLCJhdWQiOiJFdGVkQXBpLmNvbSJ9.k2Hk5HLlYwlKRy4709B3UuUV0y93lbJg4uBtBofA_Eg

###
DELETE http://localhost:5000/api/node/2

###
PUT http://localhost:5000/api/node/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIyIiwic2lkIjoiMSIsImV4cCI6MTYyOTkxMDg5NiwiaXNzIjoiRXRlZEFwaS5jb20iLCJhdWQiOiJFdGVkQXBpLmNvbSJ9.k2Hk5HLlYwlKRy4709B3UuUV0y93lbJg4uBtBofA_Eg

{
  "name": "testSub2",
  "zone": "testZone2",
  "phase": "testPhase2"
}

###
Post http://137.184.75.4:5000/api/user/signup
Content-Type: application/json

{
  "username": "Manuel",
  "password": "manuel",
  "name": "manuel",
  "lastname": "lopez",
  "groupId": 1
}
###
Post http://137.184.75.4:5000/api/user/login
Content-Type: application/json

{
  "username": "Manuel",
  "password": "manuel"

}

###
GET http://localhost:5000/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIyIiwic2lkIjoiMSIsImV4cCI6MTYyOTkxMDg5NiwiaXNzIjoiRXRlZEFwaS5jb20iLCJhdWQiOiJFdGVkQXBpLmNvbSJ9.k2Hk5HLlYwlKRy4709B3UuUV0y93lbJg4uBtBofA_Eg

###
PUT http://localhost:5000/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIyIiwic2lkIjoiMSIsImV4cCI6MTYyOTkxMDg5NiwiaXNzIjoiRXRlZEFwaS5jb20iLCJhdWQiOiJFdGVkQXBpLmNvbSJ9.k2Hk5HLlYwlKRy4709B3UuUV0y93lbJg4uBtBofA_Eg

{
  "username": "testUserUpdate",
  "name": "testNameUpdate",
  "lastName": "testLastnameUpdate",
  "password": "testPasswordUpdate"
}
###
Post http://137.184.75.4:5000/api/user/isLogged
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIxIiwic2lkIjoiMSIsImV4cCI6MTYzMTA0NDc1MSwiaXNzIjoiRXRlZEFwaS5jb20iLCJhdWQiOiJFdGVkQXBpLmNvbSJ9.ml-NDwulfVCtDhsCZebELppp3U5Cz5c54hXbml8ggsg

### 
Post http://localhost:5000/api/visitform/filter
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiIyIiwic2lkIjoiMSIsImV4cCI6MTYyOTkxMDg5NiwiaXNzIjoiRXRlZEFwaS5jb20iLCJhdWQiOiJFdGVkQXBpLmNvbSJ9.k2Hk5HLlYwlKRy4709B3UuUV0y93lbJg4uBtBofA_Eg

{
  "filterNodes": [],
  "filterPhase": [],
  "filterFromDate": null,
  "filterUntilDate": null,
}

### 
GET http://localhost:5000/api/visitform
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdHVzZXIxIiwianRpIjoiMSIsImV4cCI6MTYyOTM5NjQ5NSwiaXNzIjoiRXRlZEFwaS5jb20iLCJhdWQiOiJFdGVkQXBpLmNvbSJ9.jyurXmO_aFWydfG2O2qf3FNJsb8IO_fJDtPsFjJtFZM

###
Get http://localhost:5000/api/group
Content-Type: application/json

###
Post http://localhost:5000/api/visitform/images
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidGVzdHVzZXIxIiwianRpIjoiMSIsImV4cCI6MTYyOTM5NjQ5NSwiaXNzIjoiRXRlZEFwaS5jb20iLCJhdWQiOiJFdGVkQXBpLmNvbSJ9.jyurXmO_aFWydfG2O2qf3FNJsb8IO_fJDtPsFjJtFZM

{
  ids: [1,2]
}

###
DELETE http://localhost:5000/api/visitform/1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiI3Iiwic2lkIjoiMSIsImV4cCI6MTYyOTk4NjQ2NywiaXNzIjoiRXRlZEFwaS5jb20iLCJhdWQiOiJFdGVkQXBpLmNvbSJ9.70p14t_3dLLkJgPXC2ot8LB2-VQL8OhA_3bawHzA-Po
